---
- name: Ensure project directory exists
  ansible.builtin.file:
    path: "{{ compose_project_dir }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Template Docker Compose configuration
  ansible.builtin.template:
    src: docker-compose.j2
    dest: "{{ compose_project_dir }}/docker-compose.yml"
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: Template init.sql
  ansible.builtin.template:
    src: initsql.j2
    dest: "{{ compose_project_dir }}/init.sql"
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: Template Logstash configuration
  ansible.builtin.template:
    src: logstash.conf.j2
    dest: "{{ compose_project_dir }}/logstash.conf"
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: Ensure Docker Compose is installed
  ansible.builtin.stat:
    path: /usr/local/bin/docker-compose
  register: docker_compose_stat

- name: Fail if Docker Compose is not installed
  ansible.builtin.fail:
    msg: "Docker Compose is not installed at /usr/local/bin/docker-compose. Please install it."
  when: not docker_compose_stat.stat.exists

- name: Start Docker Compose services
  ansible.builtin.command:
    cmd: /usr/local/bin/docker-compose -f {{ compose_project_dir }}/docker-compose.yml up -d
    chdir: "{{ compose_project_dir }}"
  register: compose_up
  changed_when: compose_up.rc == 0