---
- name: Deploy application using Docker Compose
  hosts: localhost
  tasks:
    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_check
      ignore_errors: yes
      changed_when: false

    - name: Fail if Docker is not installed
      ansible.builtin.fail:
        msg: "Docker is not installed. Please install Docker on the host."
      when: docker_check.rc != 0

    - name: Include Docker Compose deployment role
      ansible.builtin.include_role:
        name: docker-compose