- name: Copy Kubernetes manifests deployment script
  ansible.builtin.template:
    src: manifests.j2
    dest: /tmp/deploy_manifests.sh
    mode: '0755'

- name: Deploy Kubernetes manifests
  ansible.builtin.command: /tmp/deploy_manifests.sh