---
   - name: Copy Kubernetes manifests deployment script
     ansible.builtin.template:
       src: manifests.j2
       dest: /tmp/deploy_manifests.sh
       mode: '0755'

   - name: Copy and decrypt MySQL secret
     ansible.builtin.copy:
       src: secrets/mysql-secret.yml
       dest: /tmp/mysql-secret.yaml
       mode: '0644'
       decrypt: yes

   - name: Deploy Kubernetes manifests
     ansible.builtin.command: /tmp/deploy_manifests.sh
     become: yes
     become_user: jenkins




     