- name: Copy Kubernetes manifests deployment script
  ansible.builtin.template:
    src: manifests.j2
    dest: /tmp/deploy_manifests.sh
    mode: '0755'

- name: Deploy Kubernetes manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  loop:
    - "{{ manifests_dir }}/mysql-secret.yaml"
    - "{{ manifests_dir }}/mysql.yaml"
    - "{{ manifests_dir }}/model-service.yaml"
    - "{{ manifests_dir }}/middleware.yaml"
    - "{{ manifests_dir }}/frontend.yaml"
    - "{{ manifests_dir }}/elasticsearch.yaml"
    - "{{ manifests_dir }}/kibana.yaml"
    - "{{ manifests_dir }}/logstash.yaml"